import { NextRequest, NextResponse } from 'next/server'
import { GoogleGenerativeAI } from '@google/generative-ai'

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { question, context, studentLevel, pageContent } = body;

    if (!process.env.GEMINI_API_KEY) {
      return NextResponse.json(
        { error: 'GEMINI_API_KEY is not set in environment variables.' },
        { status: 500 }
      );
    }

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

    const prompt = `
You are SynapseMedAI, an expert medical tutor and assistant.
Student Level: ${studentLevel || 'General'}
User Context: ${context || 'General'}

Website Context (Current Page Data):
${pageContent || 'No page data provided.'}

User Question: ${question}

Instructions:
1. Provide a detailed, accurate, and educational answer.
2. If the "Website Context" contains relevant information, use it to accurately answer the question and reference it.
3. Keep the response professional but easy to read.
`;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();

    return NextResponse.json({
      question: question,
      answer: responseText,
      sources: ["Generated by SynapseMed (Gemini AI)"]
    })
  } catch (error) {
    console.error('AI Answer service error:', error)
    return NextResponse.json(
      { error: 'Failed to get AI answer', message: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}